Add release CI
liquidz/clj-xmas pull request #5
Opened 2021-12-18 07:40 UTC by eggplants

`git push x.y.z`でMacOSとLinuxのバイナリをリリースできるCIを追加しました。(#4 はrebaseの関係で関係ない変更が入っていたのでcloseしました)

2021-12-18 21:34 UTC, liquidz requested changes
@eggplants リリースCIの追加ありがとうございました！
いくつか気になる点がありコメントしたのでご確認ください。

2021-12-18 21:34 UTC, liquidz commented on .github/workflows/release.yml
> +          # boot: latest
Leiningen は使っていないはずですが必要だったでしょうか？
また setup-clojure では `:cli` にも `latest` は指定可能なので `latest` の方が望ましいです
```suggestion
          cli: latest
```

2021-12-18 21:34 UTC, liquidz commented on .github/workflows/release.yml
> +          clojure -Ttools install ${{ env.repo }}/${{ env.app-name }} "{:local/root \"${PWD}\"}" :as ${{ env.pkg }}
ツールのインストールをしている意図はなんでしょうか？

2021-12-18 21:34 UTC, liquidz commented on .github/workflows/release.yml
> +            "-J-Xmx3g"
Makefile の内容と重複してしまっているので、別途スクリプトに切り出すなどした方が2重管理を防げて嬉しいです

2021-12-18 21:34 UTC, liquidz commented on .github/workflows/release.yml
> +          clojure -Ttools install ${{ env.repo }}/${{ env.app-name }} "{:local/root \"${PWD}\"}" :as ${{ env.pkg }}
こちらも同様にツールをインストールしている意図はなんでしょうか？

2021-12-18 21:34 UTC, liquidz commented on .github/workflows/release.yml
> +          prerelease: false
念のための確認までですが、workflow 経由ではなく GitHub 上でリリースを作成した時もタグが作られるのでこの workflowが実行されるかと思います。
その場合、すでに同名のリリースが存在している状態だと思うのですが後続の処理も含めて特に問題なく動作したでしょうか？

「リリース時には手元から `git tag x.y.z && git push origin x.y.z` とする」でも良いのですが、GitHub 上のUIでリリースできる方が誤操作を防げて嬉しいです。

2021-12-19 03:03 UTC, eggplants commented on .github/workflows/release.yml
> +          clojure -Ttools install ${{ env.repo }}/${{ env.app-name }} "{:local/root \"${PWD}\"}" :as ${{ env.pkg }}
コメントアウトしました。なくてもビルドできるんですね‥

2021-12-19 03:04 UTC, eggplants commented on .github/workflows/release.yml
> +          prerelease: false
すでにリリースが存在している場合はここをスキップするようにします。前提としてコマンドラインからのtag pushのみを対象にしていました。

2021-12-19 03:17 UTC, eggplants commented on .github/workflows/release.yml
> +            "-J-Xmx3g"
```bash
make GRAAL_HOME="$(
  which native-image|sed 's_/bin/native-image__'
)" GRAAL_EXTRA_OPTION="$(
  [ ${{ matrix.os }} = darwin ] || echo '--static'
)" native-image -o graalvm uberjar
```

2021-12-19 03:42 UTC, eggplants commented on .github/workflows/release.yml
> +          # boot: latest
cliがlatestの場合、Windowsにclojureがインストールされませんでした…

2021-12-19 03:44 UTC, eggplants commented on .github/workflows/release.yml
> +          # boot: latest
失敗(`cli: latest`): https://github.com/eggplants/clj-xmas/actions/runs/1597572281
成功(`latest`->`"1.10.3.1040"`): https://github.com/eggplants/clj-xmas/actions/runs/1597588106

2021-12-19 03:49 UTC, eggplants commented on .github/workflows/release.yml
> +          # boot: latest
https://github.com/DeLaGuardo/setup-clojure/issues/36

2021-12-19 03:57 UTC, eggplants commented on .github/workflows/release.yml
> +          # boot: latest
`https://download.clojure.org/install/win-install-latest.ps1`が存在せず、`https://download.clojure.org/install/win-install-1.10.3.1040.ps1`は存在しています。そこで落ちているようです。

2021-12-19 03:58 UTC, eggplants commented on .github/workflows/release.yml
> +          # boot: latest
https://github.com/DeLaGuardo/setup-clojure/blob/0fe110ad5aab7de04967d0f573267f7009aa0609/src/cli.ts#L79

2021-12-19 04:19 UTC, eggplants commented on .github/workflows/release.yml
> +          prerelease: false
案の定Web UI上からの新しいタグ作成->releaseでは`actions/create-release@v1`が以下のエラーで落ちます。
```
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

2021-12-19 04:23 UTC, eggplants commented on .github/workflows/release.yml
> +          prerelease: false
`softprops/action-gh-release@v1`を試します。
ref: https://github.com/actions/create-release/issues/29#issuecomment-643823811

2021-12-19 05:26 UTC, eggplants commented on .github/workflows/release.yml
> +          prerelease: false
うまく行かなかったのでtag pushでtriggerしてください。
create releaseをCIで使用している時Web UIからのreleaseかどうかを判別する方法があれば教えてください。

2021-12-19 13:59 UTC, eggplants commented on .github/workflows/release.yml
> +          prerelease: false
https://github.com/DeLaGuardo/setup-clojure/issues/36#issuecomment-997374456
修正していただき`latest`で正常にインストールされるようになりました。

2021-12-20 21:30 UTC, liquidz commented on .github/workflows/release.yml
> +          prerelease: false
> create releaseをCIで使用している時Web UIからのreleaseでうまくやる方法をご存知であれば教えてください。

今のところパッと思いつく方法はないですね。
やるとするならばバージョン番号を自前で管理して `workflow_dispatch` をトリガーとしたワークフロー内でタグ付けをしてあげるようにすれば GitHub 上の UI のみでリリース可能かなと思っています。

2021-12-20 21:32 UTC, liquidz approved these changes
@eggplants LGTM! ありがとうございました！

2021-12-20 21:32 UTC, merged

2021-12-22 20:54 UTC, eggplants commented
https://github.com/eggplants/clj-xmas/releases/tag/0.0.0
に置いていますが、各環境のバイナリアーカイブを1.0.0のReleaseにも置いてほしいです。